export const GET_ALL = 'GET_ALL'
export const SET_USER = 'SET_USER'
export const GET_NAME = 'GET_NAME'
export const GET_PHONE = 'GET_PHONE'
export const GET_BALANCE = 'GET_BALANCE'
export const NEW_USER = 'NEW_USER'
export const GET_TOKEN = 'GET_TOKEN'
export const SET_TOKEN = 'SET_TOKEN'
export const GET_PROFILE = 'GET_PROFILE'

export const IS_LOGGED = 'IS_LOGGED'
export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'

export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL'
export const SHOW_REGISTER_MODAL = 'SHOW_REGISTER_MODAL'